// actions related to the app
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_ENV = 'CHANGE_ENV'
export const CHANGE_CHOSEN_DOMAIN = 'CHANGE_CHOSEN_DOMAIN'
export const CHANGE_CHOSEN_TYPEFORM = 'CHANGE_CHOSEN_TYPEFORM'
